### ISSUE TITLE
Use of PNGFiles instead of ImageMagick

### ISSUE THREAD

**Issue by kimikage** [JuliaImages/ImageShow.jl#20]
I think ImageShow.jl  only use the PNG generation function of ImageMagick, so ImageMagick can be replaced by the new package [PNGFIles](https://github.com/JuliaIO/PNGFiles.jl).

Perhaps when we use ImageShow without image files other than PNG, PNGFiles is better. However, in many cases, other packages in use depend on ImageMagick, so it is not always better.

**Comment by johnnychen94** [comment]
Good idea, but I think that requires PNGFiles to support `savestreaming` method.

cc: @ianshmean

**Comment by kimikage** [comment]
Well, I assumed the usage without the FileIO and streaming. In any case, we need to extend PNGFiles.

**Comment by johnnychen94** [comment]
With https://github.com/JuliaIO/PNGFiles.jl/pull/14 merged, I think this is good to close; FileIO would use ImageIO if available.

**Comment by ianshmean** [comment]
PNGFiles does indeed support streams now, and I’ll be adding support in ImageIO once PNGfiles releases. Should all be released today

**Comment by ianshmean** [comment]
Released as of ImageIO 0.2.0 👍
