### ISSUE TITLE
Array{ARGB{T},2} displays as if the argb components were permuted in Juno

### ISSUE THREAD

**Issue by elronayellin** [JuliaImages/ImageShow.jl#24]
On macOS 10.15.4, Radeon Pro 560/Intel HD 630, JuliaPro 1.4.1, julia-client 0.12.4, ink 0.12.3, ImageShow 0.2.3
````
julia> c = ARGB(RGB(1,0,0),1) #displays a red patch

julia> c.:r
1.0N0f8

julia> c.:alpha
1.0N0f8

julia> c.:b
0.0N0f8

julia> A=fill(c,1,1) #displays a blue patch!

julia> A[1,1] #displays a red patch
````

The problem doesn't seem to depend on the `ARGB` `eltype`.
ImageView displays correctly.

**Comment by johnnychen94** [comment]
Similar to https://github.com/JuliaIO/PNGFiles.jl/issues/8, looks like it's because QuartzImageIO doesn't support ARGB types

A temporary workaround is to uninstall QuartzImageIO and use only ImageMagick and ImageIO.

cc: @rsrock @timholy

**Comment by elronayellin** [comment]
Ok, thanks for the pointer. Redirected to https://github.com/JuliaIO/QuartzImageIO.jl/issues/63
