### ISSUE TITLE
Change output on IJulia to scale between min and max by default?

### ISSUE THREAD

**Issue by tlnagy** [JuliaImages/ImageShow.jl#43]
Currently, the default output on IJulia is quite useless in many cases since the image isn't scaled (left), while a simple scaling works well (right):

![image](https://user-images.githubusercontent.com/1661487/31637501-daf4d0e0-b283-11e7-9fd2-0655436ade19.png)

I think a sane default is to linearly scale between the minimum and maximum value (the approach already taken by ImageView).

**Comment by roflmaostc** [comment]
Let's close this because of #55 ?

**Comment by timholy** [comment]
SGTM
