### ISSUE TITLE
Output embeddable HTML directly

### ISSUE THREAD

**Issue by lorenzoh** [JuliaImages/ImageShow.jl#48]
I've run into two use cases where I'd like to show an image to `text/html` directly to get embeddable output:

- to render code block results in Pollen.jl
  <img width="612" alt="image" src="https://user-images.githubusercontent.com/28812146/165891468-46091ba3-1062-4335-a43f-a83be0b7836d.png">

- for rich HTML display of images inside other HTML structures, like a table
  For example, inside a PrettyTables.jl table using HTML output: 
  <img width="601" alt="image" src="https://user-images.githubusercontent.com/28812146/165891374-697c4304-f0b0-4eab-ab95-e7b0834440dc.png">

Is there an implementation of `show(::IO, ::MIME"text/html", ::ColorantMatrix)` somewhere?

---

**Workaround**

For now, I've been using the below functions to render images (and other data that can be rendered to image mimetypes like plots) to HTML. However, it would be nice to have a method, at least for images (`ColorantMatrix`es) for showing to `text/html` that falls back on png/jpg/svg output.

```julia
function Base.show(io::IO, mime::MIME"text/html", x::ShowAsHTML)
    if showable(mime, x.val)
        show(io, mime, x.val)
    elseif showable(MIME("image/jpg"), x.val)
        buf = IOBuffer()
        show(buf, MIME("image/jpg"), x.val)
        print(io, """<img src="data:image/png;base64,$(Base64.base64encode(take!(buf)))"/>""")
    elseif showable(MIME("image/png"), x.val)
        buf = IOBuffer()
        show(buf, MIME("image/png"), x.val)
        print(io, """<img src="data:image/png;base64,$(Base64.base64encode(take!(buf)))"/>""")
    elseif showable(MIME("image/svg+xml"), x.val)
        buf = IOBuffer()
        show(buf, MIME("image/svg+xml"), x.val)
        print(io, replace(String(take!(buf)), "\n" => ""))
    else
        print(io, x)
    end
end
```

**Comment by johnnychen94** [comment]
This looks a good improvement to me, do you mind opening a PR for this?

**Comment by lorenzoh** [comment]
Sure, will do!

The PR would include primarly a method `show(::IO, ::MIME"text/html", ::ColorantMatrix)`. Is the precedence jpg > png > svg fine? I was going for smallest size if possible.

```julia
using ImageShow

show(io, MIME("text/html"), image)
```

Additionally, I would like to add a wrapper type that can wrap any type with some image mimes (not just `ColorantMatrix`es`) to force it to try using image mimes to display HTML. This wrapper type could also accept as optional argument a different precedence of preferred image encodings. Maybe `HTMLImage` is a good name?

So you could do

```julia
using ImageShow, CairoMakie

fig = scatter(rand(1:10))

show(io, MIME("text/html"), HTMLImage(fig))  # would  result in a png
show(io, MIME("text/html"), HTMLImage(fig; mimes = ["image/svg", "image/png"]))  # would result in an svg
```

Does this design make sense?

**Comment by johnnychen94** [comment]
I think it only makes sense for ImageShow to support `show(io, MIME("text/html"), image)`.

The HTMLImage seems more like a wrapper type that you can defined anywhere you want since it can be only a few lines:

```julia
struct HTMLImage{T}
    x::T
    mimes::Vector{MIME}
end
Base.show(io, fig::HTMLImage) = show(io, findfirst(mime->showable(mime, fig.x), fig.mimes), fig)
Base.show(io, ::MIME("text/html"), fig::HTMLImage) = show(io, MIME("text/html"), fig.x)
```

For type stability, it's better to be `mime = [MIME("image/svg"), MIME("image/png")]` with an optional friendly depwarn for `mime = ["image/svg", "image/png"]`.

**Comment by lorenzoh** [comment]
Will take these into account!

Re the `HTMLImage`: I don't think your definition, since the html tags and base64 encoding have to be created somewhere. The wrapper is meant specifically for when you want to say: if this object does not have an html mime, please fall back to the image mimes and convert them to HTML.

In any case, if that is too specific a thing to be included in the library, I completely understand!

**Comment by johnnychen94** [comment]
A second thought, it seems that you're suggesting a `PollenHTMLDisplay` stuff:

1. iterate the `Multimedia.displays` until `displayable, ` returns true
2. call `display(d, mime, fig)`, which calls
3. `show(d.io, mime, fig)`

**Comment by lorenzoh** [comment]
That still doesn't define an html display for image-like things?

**Comment by lorenzoh** [comment]
I was just checking how Documenter.jl writes image-like things to HTML and found it here: https://github.com/JuliaDocs/Documenter.jl/blob/master/src/Writers/HTMLWriter.jl#L1958

Seems like they have higher precedence for mime `"text/html"` than the image mimes, so adding the proposed code to ImageShow.jl would mean that (for images only) ImageShow's method would be called. Only difference in Documenter.jl is that they have some extra handling for `"image/svg+xml"` to make sure it is valid.
Now my concern is that without porting this svg processing, some documentation that outputs svgs somewhere would silently fail. But  `"svg/xml"` will not be used for images anyway, correct? Judging from
https://github.com/JuliaImages/ImageShow.jl/blob/324e8a4c39ade79ef689e6bf97b1f2ea54682050/src/showmime.jl#L18

Just to be on the safe side, I would set the mimes that `show(io, ::MIME"text/html", ::ColorantMatrix)` to just `[MIME("image/jpg"), MIME("image/png")]` for now.
