### ISSUE TITLE
appveyor disabled?

### ISSUE THREAD

**Issue by johnnychen94** [JuliaImages/ImageShow.jl#9]
Looks like the last time appveyor ran is 8 months ago.

**Comment by RalphAS** [comment]
Tests were running under my appveyor setup, where jobs often need to be started manually. I don't see how to trigger a build of someone else's PR until it has been merged to master. Is there a more reliable appveyor setup under the JuliaImages organization which could be used instead?

**Comment by johnnychen94** [comment]
I see a `Branches to build` option in https://ci.appveyor.com/project/RalphAS/imageshow-jl/settings, is that set to "all branches"? Or possibly the following options should not be enabled.

- Do not build feature branches with open Pull Requests
- Do not build on "Push" events
- Do not build on "Pull request" events

**Comment by RalphAS** [comment]
It's probably a permissions issue.  Perhaps it works more smoothly for organization owners? If one of them is willing to manage another email address, they might follow [the official appveyor approach for organizations](https://www.appveyor.com/docs/team-setup/#setting-up-appveyor-account-for-github-organization)
